name: Executar Script no Ubuntu 24.04

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Permitir execução do script
        run: chmod +x script.sh

      - name: Executar o script
        run: ./script.sh
